export const W = 375 // iphone X width's
export const H = 812 // iphone X height's
export const SEE_RADIUS = 80
export const BACKGROUND_COLOR = '#EE6352'
export const GRAVITY = -0.25
export const FRICTION_AIR = 0.01
export const FRICTION_GROUND = 0.07
export const WIND_MAX_FRAMES = 180
export const DISC_MAX_FRAMES = 180
